DROP TABLE tbl_board PURGE;

CREATE TABLE tbl_board (
    bno     NUMBER
	        GENERATED ALWAYS AS IDENTITY
	        -- GENERATED BY DEFAULT AS IDENTITY
            --GENERATED BY DEFAULT ON NULL AS IDENTITY
            --(
            	START WITH 1
            	INCREMENT BY 1
            	NOCACHE
            --)
            PRIMARY KEY,
        
    title   VARCHAR2(200) NOT NULL,
    content VARCHAR2(2000) NOT NULL,
    writer  VARCHAR2(50) NOT NULL,
    insert_ts   TIMESTAMP DEFAULT sysdate NOT NULL,
    update_ts   TIMESTAMP
);


DESC tbl_board;

SELECT * FROM RECYCLEBIN;

DROP SEQUENCE seq_board;
CREATE SEQUENCE seq_board;

INSERT INTO tbl_board (title, content, writer) 
VALUES (
	'TITLE_'||seq_board.NEXTVAL,
	'CONTENT_'||seq_board.CURRVAL,
	'writer_'||seq_board.CURRVAL
);


INSERT INTO tbl_board (title, content, writer) 
SELECT 
    'TITLE_' || seq_board.NEXTVAL,
    'CONTENT_' || seq_board.CURRVAL,
    'writer_' || seq_board.CURRVAL
FROM dual
CONNECT BY level <= 30;


COMMIT;



